spring.application.name=customer-micro-service
spring.datasource.url=jdbc:mysql://localhost:3306/customer_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ENC(gQAGdalyT7OkKT2t2ySu5hkU5+YLgTrvBoaAyu6qBhxbxyblDtO97IYwbq6NS+Hp)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.cloud.compatibility-verifier.enabled=false